theme: jekyll-theme-time-machine
title: My name is Scott. Welcome to my homepage! 
description: This homepage will follow my journey towards data science and python. Feel free to bookmark to follow my journey.
