theme: jekyll-theme-time-machine
title: My name is Scott. Welcome to my homepage! 
description: This homepage will follow my journey towards becoming a data scientist and python programmer. Feel free to bookmark to follow my journey.
